POST http://localhost:3601/v1.0/publish/pubsub/abc
content-type: application/json

{
    "name": "test"
}


POST http://localhost:3601/v1.0/publish/pubsub/publish
content-type: application/json

{
    "id": 3,
    "amount": 66
}
